openapi: 3.0.0
info:
  title: Weather Forecast API
  description: API for retrieving weather forecasts using AWS Lambda functions
  version: 1.0.0

servers:
  - url: http://localhost:8080  # Replace with your actual server URL

paths:
  /weather/current:
    get:
      summary: Get current weather
      operationId: getCurrentWeather
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string  # Assuming Lambda returns a JSON string
        '500':
          description: Error response

  /weather/weekly:
    get:
      summary: Get weekly forecast
      operationId: getWeeklyForecast
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string  # Assuming Lambda returns a JSON string
        '500':
          description: Error response

  /weather/alerts:
    get:
      summary: Get weather alerts
      operationId: getWeatherAlerts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string  # Assuming Lambda returns a JSON string
        '500':
          description: Error response
